[tool.poetry]
name = "dxpyfeed"
version = "0.0.1"
description = "Python API via C API"
authors = ["Ivan"]
build = "build.py"

[tool.poetry.dependencies]
python = "^3.6"
cython = "^0.29.13"

[tool.poetry.dev-dependencies]
python = "^3.6"
cython = "^0.29.13"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
