[tool.poetry]
name = "dxfeed"
version = "0.0.1"
description = "DXFeed Python API via C API"
authors = ["Ivan Mishalkin <ivan.mishalkin@devexperts.com>",
           "DxCurrent Team <dxcurrent@devexperts.com>"]
build = "build.py"
license = "MPL-2.0"
readme = "README.md"

include = ["LICENSE", "dxfeed/**/*.c"]
exclude = ["dxfeed/dxfeed-c-api/wrappers*",
           "dxfeed/dxfeed-c-api/tests*",
           "dxfeed/dxfeed-c-api/scripts*",
           "dxfeed/dxfeed-c-api/lib*",
           "dxfeed/dxfeed-c-api/docs*",
           "dxfeed/dxfeed-c-api/.github*"]
repository = "https://github.com/dxFeed/dxfeed-python-api"

[tool.poetry.dependencies]
python = "^3.6"
cython = "^0.29.13"
pandas = "^0.25.1"

[tool.poetry.dev-dependencies]
taskipy = "^1.1.3"

[tool.taskipy.tasks]
sdist = "python build.py && poetry build -f sdist"

[build-system]
requires = ["poetry>=0.12", "cython"]
build-backend = "poetry.masonry.api"