[tool.poetry]
name = "dxpyfeed"
version = "0.0.3"
description = "Python API via C API"
authors = ["Ivan"]
build = "build.py"

[tool.poetry.dependencies]
python = "^3.6"
cython = "^0.29.13"
pandas = "^0.25.1"

[tool.poetry.dev-dependencies]
python = "^3.6"
cython = "^0.29.13"
pandas = "^0.25.1"
sphinx = "^2.2"
m2r = "^0.2.1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
