# This workflow will check package installation and runs tests
# On Ubuntu, Windows and MacOS
# Triggered by push to master

name: Test package

on:
  push:
    branches:
      - EN-1642-reconfig-cicd

jobs:
  installation:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: [3.6, 3.7, 3.8]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install poetry
      run: |
        pip install poetry
      shell: bash
    - name: Set poetry env
      run: |
        poetry install --no-root --no-dev
        poetry add taskipy cython
        poetry run task build -f sdist
        poetry remove taskipy cython
      shell: bash
    - name: Install package artifact
      run: |
        poetry add dist/dxfeed*
        poetry remove dxfeed
      shell: bash
  tests:
    needs: installation
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: [3.6, 3.7, 3.8]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install poetry
      run: |
        pip install poetry
      shell: bash
    - name: Set poetry env
      run: |
        poetry install --no-root
      shell: bash
    - name: Run tests
      run: |
        poetry run task test
      shell: bash
    - name: Generate doc
      run: |
        poetry run task html_docs
      shell: bash
      if: matrix.os == 'ubuntu-latest' && matrix.python-version == 3.7
